### PR TITLE
Improve support for mbed framework

### PR DESCRIPTION
**Pull request by valeros**

### CODE REVIEW

**Comment by pelikhan** [comment]
Is it possible to specify mbed library dependencies?

Sent from my Windows Phone
________________________________

**Comment by ivankravets** [comment]
Dear @pelikhan, 

Which dependencies do you mean?

**Comment by pelikhan** [comment]
The mbed environment provides its own system of libraries and repositories. I am curious to understand how platformio integrates with mbed.

**Comment by ivankravets** [comment]
Aaa, I got you. Do you mean mbed-libs "rtos, net, usb, etc."? Currently, PlatformIO supports only core `mbed` library. This is "initial" support. We are working on it. I hope, we will finish with all mbed libs in next week.

As for "how to enable additional mbed libs?", I don't know, but we can discuss it here.

The environment looks like:
```ini
[env:my_mbed_enabled_board]
platform = ***
framework = mbed
board = ***
```

and we can specify additional libs
```ini
[env:my_mbed_enabled_board]
platform = ***
framework = mbed
board = ***
build_flags = -lmbed-rtos -lmbed-net
```

WDYT?

P.S: Do you have any mbed-enabled device?

**Comment by pelikhan** [comment]
http://www.bbc.co.uk/mediacentre/mediapacks/makeitdigital/micro-bit

**Comment by ivankravets** [comment]
> http://www.bbc.co.uk/mediacentre/mediapacks/makeitdigital/micro-bit

Are you sure that mbed supports this board?

**Comment by pelikhan** [comment]
http://community.arm.com/groups/internet-of-things/blog/2015/03/12/arm-and-the-bbc-collaborate-on-a-new-initiative

**Comment by ivankravets** [comment]
Great! If mbed supports this board, PlatformIO will also support it :smile:

**Pull request merged**
